[package]
name = "merino-tool"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
byteorder = "1.5.0"
clap = { version = "4.5.38", features = ["derive"] }
csv = "1.3.1"
serde = { version = "1.0", features = ["derive"] }
ppc750cl = "0.3.2"
